version: '3.8'

services: 
  web: 
    build: .
    command: python3 -m flask run --host=0.0.0.0 --port=5002
    volumes:
      - .:/app
    ports: 
      - 5002:5002
    environment: 
      - FLASK_APP=app/app.py
